name: Firefox Bug Handling
markdown: kramdown
kramdown:
  auto_ids: true
author: emma@mozilla.com
collections:
  policies:
    output: true
    permalink: :title
  processes:
    output: true
    permalink: :title
  guides:
    output: true
    permalink: :title
